platform :ios, '10.0'

use_frameworks!

target 'RestStop_Example' do
  pod 'RxSwift',   '~> 4.0'
  pod 'RestStop', path: '../'
end

target 'RestStop_Tests' do
  pod 'RxSwift',   '~> 4.0'
  pod 'RestStop', path: '../'
  pod 'RxBlocking', '~> 4.0'
  pod 'RxTest',     '~> 4.0'
end
